url: http://raketanalunu.ru
title: Evgenia frontend developer
encoding: UTF-8

#baseurl: "http://raketanalunu.github.io"

description: "My personal website. Enjoy!"


# Build settings
markdown: kramdown


# Content
vk: "http://vk.com/raketanalunu"
instagram: "https://www.instagram.com/raketanalunu/" 